on:
  push:
    branches:
    - main

jobs:
  build:
    uses: cloud-cli/workflows/.github/workflows/docker-ghcr-build.yml@main
    with:
      name: codrblog/auto
      defaultBranch: main
      baseImage: 'node:latest'
